SpanJson.Benchmarks/Program.cs
SpanJson.Benchmarks/SelectedBenchmarks.cs
SpanJson.Tests/DateTests.cs
SpanJson/Helpers/DateTimeFormatter.Utf16.cs
SpanJson/Helpers/DateTimeFormatter.Utf8.cs
SpanJson/Helpers/DateTimeFormatter.cs
SpanJson/Helpers/DateTimeParser.Utf8.cs
SpanJson/JsonWriter.Utf16.cs
SpanJson/JsonWriter.Utf8.cs

Custom DateTimeFormatter

---

SpanJson.Tests/DateTests.cs
SpanJson/Helpers/DateTimeFormatter.Utf16.cs
SpanJson/Helpers/DateTimeFormatter.Utf8.cs
SpanJson/SpanJson.csproj

Fix Leading Zeros bug

---

SpanJson.Benchmarks/SelectedBenchmarks.cs
SpanJson.WebBenchmark/SpanJson.WebBenchmark.csproj
SpanJson/Formatters/Dynamic/SpanJsonDynamic.cs
SpanJson/JsonReader.cs
SpanJson/JsonWriter.cs

and update externals on webbenchmark.

Inline Constructors

---

SpanJson/JsonSerializer.Generics.cs
SpanJson/SpanJson.csproj

it might be overwritten in parallel.

don't use the static value for write size

---

SpanJson.Benchmarks/Serializers/JilSerializer.cs
SpanJson.Benchmarks/Serializers/Utf8JsonSerializer.cs
SpanJson.Tests/IncludeNullTests.cs
SpanJson.Tests/Tests.cs
SpanJson.Tests/ValueHelper.cs
SpanJson/Formatters/BclFormatter.cs
SpanJson/Formatters/BclFormatter.tt
SpanJson/Formatters/ComplexFormatter.cs

- use GetValueOrDefault instead of Value (no extra check of .HasValue there)
- Improve tests around nullability

Improve nullable support

---

SpanJson.Benchmarks/Fixture/TimespanFixture.cs
SpanJson.Benchmarks/SelectedBenchmarks.cs
SpanJson.Tests/Generated/TimeSpanTests.cs
SpanJson/JsonReader.Utf16.cs
SpanJson/JsonWriter.Utf16.cs

Use the UTf8 versions for now, event for Utf16

Performance of Timespan and Guid

---

README.md
SpanJson.Tests/CustomSerializerTests.cs
SpanJson.Tests/DictionaryTests.cs
SpanJson.Tests/DynamicTests.cs
SpanJson/Formatters/ComplexFormatter.cs
SpanJson/Formatters/DynamicMetaObjectProviderFormatter.cs
SpanJson/Formatters/EnumFormatter.cs
SpanJson/IJsonFormatter.cs
SpanJson/IJsonFormatterResolver.cs
SpanJson/JsonConstructorAttribute.cs
SpanJson/JsonCustomSerializerAttribute.cs
SpanJson/JsonReader.Utf8.cs
SpanJson/JsonWriter.Utf8.cs
SpanJson/Resolvers/JsonMemberInfo.cs
SpanJson/Resolvers/ResolverBase.cs
SpanJson/SpanJson.csproj

Support for Custom Serializers for specific members

Custom serializer

---

README.md
SpanJson.AspNetCore.Formatter.Tests/ExtensionTests.cs
SpanJson.AspNetCore.Formatter.Tests/InputFormatterTests.cs
SpanJson.AspNetCore.Formatter.Tests/OutputFormatterTests.cs
SpanJson.AspNetCore.Formatter.Tests/SpanJson.AspNetCore.Formatter.Tests.csproj
SpanJson.AspNetCore.Formatter.Tests/Startup.cs
SpanJson.AspNetCore.Formatter.Tests/TestBase.cs
SpanJson.AspNetCore.Formatter.Tests/TestController.cs
SpanJson.AspNetCore.Formatter.Tests/TestControllerFixture.cs
SpanJson.AspNetCore.Formatter.Tests/TestObject.cs
SpanJson.AspNetCore.Formatter.Tests/WebTests.cs
SpanJson.AspNetCore.Formatter/SpanJson.AspNetCore.Formatter.csproj
SpanJson.AspNetCore.Formatter/SpanJsonFormatterExtensions.cs
SpanJson.AspNetCore.Formatter/SpanJsonInputFormatter.cs
SpanJson.AspNetCore.Formatter/SpanJsonOutputFormatter.cs
SpanJson.Shared/GenericEqualityComparer.cs
SpanJson.Tests/DynamicTests.cs
SpanJson.Tests/SpanJson.Tests.csproj
SpanJson.Tests/Tests.cs
SpanJson.sln
SpanJson/SpanJson.csproj

ASP.Net Core 2.1 Formatter

---

README.md
SpanJson.AspNetCore.Formatter.Tests/CustomFormatter.cs
SpanJson.AspNetCore.Formatter.Tests/InputFormatterTests.cs
SpanJson.AspNetCore.Formatter.Tests/OutputFormatterTests.cs
SpanJson.AspNetCore.Formatter/SpanJson.AspNetCore.Formatter.csproj
SpanJson.AspNetCore.Formatter/SpanJsonFormatterExtensions.cs
SpanJson.Benchmarks/SpanJson.Benchmarks.csproj
SpanJson.Tests/EnumIntegerTests.cs
SpanJson.Tests/EnumStringTests.cs
SpanJson.Tests/IntegerEnumCustomFormatter.cs
SpanJson.Tests/SpanJson.Tests.csproj
SpanJson.Tests/Tests.cs
SpanJson.WebBenchmark/SpanJson.WebBenchmark.csproj
SpanJson/Formatters/EnumIntegerFormatter.cs
SpanJson/Formatters/EnumStringFormatter.cs
SpanJson/Resolvers/EnumOptions.cs
SpanJson/Resolvers/ExcludeNullsCamelCaseResolver.cs
SpanJson/Resolvers/ExcludeNullsOriginalCaseResolver.cs
SpanJson/Resolvers/IncludeNullsCamelCaseResolver.cs
SpanJson/Resolvers/IncludeNullsOriginalCaseResolver.cs
SpanJson/Resolvers/NamingConventions.cs
SpanJson/Resolvers/NullOptions.cs
SpanJson/Resolvers/ResolverBase.cs
SpanJson/Resolvers/SpanJsonOptions.cs
SpanJson/SpanJson.csproj

Custom Integer Enum Formatter

---

README.md
SpanJson.AspNetCore.Formatter.Tests/CustomFormatter.cs
SpanJson.AspNetCore.Formatter.Tests/InputFormatterTests.cs
SpanJson.AspNetCore.Formatter.Tests/OutputFormatterTests.cs
SpanJson.AspNetCore.Formatter/SpanJson.AspNetCore.Formatter.csproj
SpanJson.Benchmarks/SelectedBenchmarks.cs

- improve tests:
Should solve #30

EnumFormatter for Integer

---

SpanJson.Benchmarks/SelectedBenchmarks.cs
SpanJson/JsonReader.Utf16.cs
SpanJson/JsonReader.Utf8.cs

minor correctness fixes

---

SpanJson.Tests/DynamicTests.cs
SpanJson/Formatters/ComplexFormatter.cs
SpanJson/Formatters/DynamicMetaObjectProviderFormatter.cs

Comments and a few correctness fixes for dynamic

Comments and a few correctness fixes for dynamic

---

SpanJson.Tests/ArrayTests.cs
SpanJson/Formatters/TwoDimensionalArrayFormatter.cs
SpanJson/JsonParserException.cs
SpanJson/Resolvers/ResolverBase.cs

Apparently I forgot support for multi-dimensional arrays, jagged arrays worked fine.
Added support for 2D arrays, everything higher is not supported.

Two Dimensional Array support

---

README.md
SpanJson.Tests/AsyncTests.cs
SpanJson.Tests/ExtensionAttributeTests.cs
SpanJson/Formatters/ComplexFormatter.cs
SpanJson/JsonExtensionDataAttribute.cs
SpanJson/Resolvers/JsonExtensionMemberInfo.cs
SpanJson/Resolvers/JsonObjectDescription.cs
SpanJson/Resolvers/ResolverBase.cs

Initial Support for JsonExtensionDataAttribute

---

SpanJson/Formatters/NullableFormatter.cs

GetValueOrDefault does not check HasValue again.

GetValueOrDefault does not check HasValue again.

---

SpanJson.Tests/CustomSerializerTests.cs
SpanJson.Tests/GlobalCustomFormatter.cs
SpanJson/Formatters/BaseEnumStringFormatter.cs
SpanJson/IJsonFormatter.cs
SpanJson/JsonCustomSerializerAttribute.cs
SpanJson/Resolvers/JsonMemberInfo.cs
SpanJson/Resolvers/ResolverBase.cs

Arguments for Custom Serializer
Should solve #61 
Preparation for #69

Arguments for Custom Serializer

---

SpanJson.Tests/SerializationTests.cs
SpanJson/Helpers/RecursionCandidate.cs

Fix Recursion Check

---

SpanJson.Tests/SerializationTests.cs
SpanJson/Helpers/RecursionCandidate.cs
SpanJson/Helpers/TypeExtensions.cs
SpanJson/Resolvers/ResolverBase.cs

Ignore ByRefProperties and -Fields

Ignore ByRefProperties and -Fields

---

SpanJson.Benchmarks/ModelBenchmark.cs
SpanJson.Benchmarks/ModelBenchmark.tt
SpanJson.Benchmarks/ReaderBenchmark.cs
SpanJson.Benchmarks/ReaderBenchmark.tt
SpanJson.Benchmarks/SelectedBenchmarks.cs
SpanJson.Benchmarks/WriterBenchmark.cs
SpanJson.Benchmarks/WriterBenchmark.tt
SpanJson.Shared/Fixture/BooleanValueFixture.cs
SpanJson.Shared/Fixture/ByteValueFixture.cs
SpanJson.Shared/Fixture/CharValueFixture.cs
SpanJson.Shared/Fixture/DecimalValueFixture.cs
SpanJson.Shared/Fixture/DoubleValueFixture.cs
SpanJson.Shared/Fixture/EnumValueFixture.cs
SpanJson.Shared/Fixture/ExpressionTreeFixture.cs
SpanJson.Shared/Fixture/FloatValueFixture.cs
SpanJson.Shared/Fixture/IntValueFixture.cs
SpanJson.Shared/Fixture/LongValueFixture.cs
SpanJson.Shared/Fixture/SByteValueFixture.cs
SpanJson.Shared/Fixture/ShortValueFixture.cs
SpanJson.Shared/Fixture/StringValueFixture.cs
SpanJson.Shared/Fixture/UIntValueFixture.cs
SpanJson.Shared/Fixture/UlongValueFixture.cs
SpanJson.Shared/Fixture/UshortValueFixture.cs
SpanJson/Helpers/SpanExtensions.cs

Adding a fixed seed to make them more deterministic

Benchmark Cleanup

---

SpanJson.Tests/Generated/DoubleTests.cs
SpanJson.Tests/Generated/SingleTests.cs
SpanJson/Helpers/SpanHelper.cs
SpanJson/JsonWriter.Utf16.cs
SpanJson/JsonWriter.Utf8.cs
SpanJson/JsonWriter.cs

Don't write NaN,infinity in double/float

Don't write NaN,infinity in double/float

---

README.md
SpanJson.Tests/CustomSerializerTests.cs

wrong method used in Readme

---

SpanJson/JsonParserException.cs
SpanJson/JsonReader.Utf16.cs
SpanJson/JsonReader.Utf8.cs
SpanJson/JsonReader.cs
SpanJson/JsonWriter.cs

Small codefixes related to exceptions

Exceptions

---

README.md
SpanJson.Tests/Tests.cs
SpanJson/Helpers/FormatterUtils.cs
SpanJson/JsonSerializer.cs

Some basic support for minification of JSON, the inverse of the pretty print.

Minify support

---

README.md
SpanJson.Tests/DateTests.cs
SpanJson/Helpers/DateTimeParser.Utf16.cs
SpanJson/Helpers/DateTimeParser.Utf8.cs
SpanJson/Helpers/DateTimeParser.cs

And many more tests for edge cases.

Relax Parser to fix T24 case

---

SpanJson.Tests/EnumStringTests.cs
SpanJson/Formatters/EnumStringFlagsFormatter.cs

Fix Enum with default values

---

SpanJson.Tests/CustomSerializerTests.cs
SpanJson/Resolvers/ResolverBase.cs

Fix Custom Serializer on Type level

Fix Custom Serializer on Type level

---

SpanJson.Tests/EscapeHelper.cs
SpanJson.Tests/Generated/BclTests.cs
SpanJson.Tests/Generated/BclTests.tt
SpanJson.Tests/Generated/TestBase.cs
SpanJson.Tests/Tests.cs
SpanJson.Tests/UnicodeEscapeTests.cs
SpanJson/Formatters/DictionaryFormatter.cs
SpanJson/Formatters/DynamicMetaObjectProviderFormatter.cs
SpanJson/JsonConstants.cs
SpanJson/JsonReader.Utf16.cs
SpanJson/JsonReader.Utf8.cs
SpanJson/JsonReader.cs
SpanJson/JsonWriter.Utf16.cs
SpanJson/JsonWriter.Utf8.cs
SpanJson/JsonWriter.cs

Various minor improvements for escaped value types

Various minor improvements for escaped value types

---

Directory.Build.props
SpanJson.Benchmarks/MyConfig.cs
SpanJson.Benchmarks/SelectedBenchmarks.cs
SpanJson.Benchmarks/SpanJson.Benchmarks.csproj
SpanJson.Tests/SpanJson.Tests.csproj

Forget that in the previous PR

Fix Benchmarks

---

SpanJson.AspNetCore.Formatter.Tests/SpanJson.AspNetCore.Formatter.Tests.csproj
SpanJson.AspNetCore.Formatter.Tests/Startup.cs
SpanJson.AspNetCore.Formatter/SpanJson.AspNetCore.Formatter.csproj
SpanJson.Benchmarks/Serializers/SystemTextJsonSerializer.cs
SpanJson.Benchmarks/SpanJson.Benchmarks.csproj
SpanJson.Tests/SpanJson.Tests.csproj
SpanJson/SpanJson.csproj
azure-pipelines.yml

Fixes https://github.com/Tornhoof/SpanJson/issues/158

Added target framework .NET 6 and updated dependencies

---

Directory.Build.props
SpanJson.Benchmarks/MyConfig.cs
SpanJson.Benchmarks/SpanJson.Benchmarks.csproj
SpanJson/Formatters/BclFormatter.cs
SpanJson/Formatters/BclFormatter.tt
SpanJson/JsonReader.Utf16.cs
SpanJson/JsonWriter.Utf16.cs
SpanJson/JsonWriter.Utf8.cs
SpanJson/SkipLocalsInit.cs
SpanJson/SpanJson.csproj

Use CollectionMarshal for lists, enable Skip Locals Init on module level and a few related bugfixes.

More net6 changes

---

Directory.Build.props
SpanJson.Tests/BugfixTests.cs
SpanJson/JsonWriter.Utf8.cs
SpanJson/SpanJson.csproj

Fix rare string escape buffer bug.
Closes #163

Fix rare string escape buffer bug #163

---

Directory.Build.props
README.md
SpanJson.Tests/BugfixTests.cs
SpanJson/JsonWriter.Utf8.cs
SpanJson/SpanJson.csproj

Improve previous bugfix and fix formatting

---

Directory.Build.props
SpanJson.Tests/Base64ArrayFormatterTests.cs
SpanJson/JsonReader.Utf16.cs
SpanJson/JsonReader.Utf8.cs
SpanJson/JsonWriter.Utf16.cs
SpanJson/JsonWriter.Utf8.cs
SpanJson/Resolvers/ByteArrayOptions.cs
SpanJson/Resolvers/ResolverBase.cs
SpanJson/Resolvers/SpanJsonOptions.cs

Use existing, optimized B64 Code for UTF8.
@Reris That's using the types from your comment.

Use System.Buffers.Text.Base64 for Utf8

---

Directory.Build.props
README.md
SpanJson.AspNetCore.Formatter.Tests/SpanJson.AspNetCore.Formatter.Tests.csproj
SpanJson.AspNetCore.Formatter/SpanJson.AspNetCore.Formatter.csproj
SpanJson.Benchmarks/SpanJson.Benchmarks.csproj
SpanJson.Tests/SpanJson.Tests.csproj
SpanJson.WebBenchmark/SpanJson.WebBenchmark.csproj
SpanJson.WebBenchmark/Startup.cs
SpanJson/JsonReader.Utf8.cs
SpanJson/JsonSerializer.cs
SpanJson/SpanJson.csproj
azure-pipelines.yml

Changes for .NET 7 support

---

Directory.Build.props
SpanJson.Tests/ExtensionAttributeTests.cs
SpanJson/Formatters/ComplexFormatter.cs

Properly check duplicate camel casing

---

README.md
SpanJson.Benchmarks/BclBenchmark.tt
SpanJson.Benchmarks/ModelBenchmark.tt
SpanJson.Benchmarks/ReaderBenchmark.tt
SpanJson.Benchmarks/WriterBenchmark.tt
SpanJson.Shared/ExtensionMethods.cs
SpanJson.Shared/Fixture/DateOnlyFixture.cs
SpanJson.Shared/Fixture/ExpressionTreeFixture.cs
SpanJson.Shared/Fixture/TimeOnlyFixture.cs
SpanJson.Shared/SpanJson.Shared.csproj
SpanJson.Tests/DateTests.cs
SpanJson.Tests/Generated/BclTests.tt
SpanJson/Formatters/BclFormatter.tt
SpanJson/Formatters/Dynamic/SpanJsonDynamicString.Operators.tt
SpanJson/Formatters/Dynamic/SpanJsonDynamicString.cs
SpanJson/Helpers/DateTimeFormatter.Utf16.cs
SpanJson/Helpers/DateTimeFormatter.Utf8.cs
SpanJson/Helpers/DateTimeParser.Utf16.cs
SpanJson/Helpers/DateTimeParser.Utf8.cs
SpanJson/JsonConstants.cs
SpanJson/JsonParserException.cs
SpanJson/JsonReader.PrimitiveWrappers.tt
SpanJson/JsonReader.Utf16.cs
SpanJson/JsonReader.Utf8.cs
SpanJson/JsonWriter.PrimitiveWrappers.tt
SpanJson/JsonWriter.Utf16.cs
SpanJson/JsonWriter.Utf8.cs

Addresses #192. I wasn't sure if there were other tests I should make -- hence sitting on the last commit for ~3 weeks before making this PR. Finally just figured I'd ask.

Add support for DateOnly and TimeOnly
